# Generated by Django 3.2.5 on 2022-06-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='comment',
            field=models.TextField(max_length=150, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.timetable', verbose_name='Занятие'),
        ),
    ]
