# Generated by Django 3.2.5 on 2022-06-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20220603_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='comment',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Комментарий'),
        ),
    ]
