# Generated by Django 3.2.5 on 2022-06-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_auto_20220611_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='name',
            field=models.TextField(blank=True, default='Без темы', max_length=300, null=True, verbose_name='Тема занятия'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.CharField(default='', help_text='н или б или пусто', max_length=2, verbose_name='Посещаемость')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.student', verbose_name='Студент')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabinet.timetable', verbose_name='Занятие')),
            ],
        ),
    ]
